# Generated by Django 4.1.7 on 2023-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
